version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - jenkins
    command: start --all --config /etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    networks:
      - jenkins-net


volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
